#!/bin/sh /etc/rc.common

. /lib/netifd/netifd-proto.sh

START=99
STOP=10

USE_PROCD=1

service_triggers() {
	procd_add_interface_trigger "interface.*" "wan" /etc/init.d/netbird restart
}

start_service() {
	local device

	procd_open_instance
	procd_set_param command /usr/bin/netbird
	procd_set_param env NB_CONFIG="/etc/netbird/config.json"
	procd_append_param command service run
	procd_set_param pidfile /var/run/netbird.pid
	procd_close_instance
}
