#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50
STOP=50

USE_PROCD=1
PROG=/usr/sbin/gophish

start_service() {
	[ -f /usr/libexec/gophish/gophish.db ] || {
		touch /usr/libexec/gophish/gophish.db
		chown gophish /usr/libexec/gophish/gophish.db
		chmod 0640 /usr/libexec/gophish/gophish.db
		chown gophish /usr/libexec/gophish/
		chmod 750 /usr/libexec/gophish/
	}

	procd_open_instance
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param user gophish
	procd_set_param command $PROG --working-directory /www/gophish --config /etc/gophish.json
	procd_close_instance
}
