#!/bin/sh

[ -f "/etc/mwan3.user" ] && {
	. /lib/functions.sh
	. /lib/mwan3/mwan3.sh

	mwan3_lock "$ACTION" "user"

	config_load mwan3
	config_get_bool enabled globals 'enabled' '0'
	[ ${enabled} -gt 0 ] || {
		mwan3_unlock "$ACTION" "user"
		exit 0
	}

	config_get enabled "$INTERFACE" enabled 0
	[ "${enabled}" = "1" ] || {
		mwan3_unlock "$ACTION" "user"
		exit 0
	}

	mwan3_unlock "$ACTION" "user"

	env -i ACTION="$ACTION" INTERFACE="$INTERFACE" DEVICE="$DEVICE" \
		/bin/sh /etc/mwan3.user
}

exit 0
