#!/bin/sh

[ -f "/etc/mwan3.user" ] && {
	. /lib/functions.sh
	. /lib/mwan3/mwan3.sh

	[ "$MWAN3_STARTUP" = 1 ] || mwan3_lock "$ACTION" "$DEVICE-user"

	config_load mwan3
	config_get_bool enabled globals 'enabled' '0'
	[ "${enabled}" -gt 0 ] || {
		[ "$MWAN3_STARTUP" = 1 ] || mwan3_unlock "$ACTION" "$DEVICE-user"
		exit 0
	}

	config_get_bool enabled "$INTERFACE" enabled 0
	[ "${enabled}" -eq 1 ] || {
		[ "$MWAN3_STARTUP" = 1 ] || mwan3_unlock "$ACTION" "$DEVICE-user"
		exit 0
	}

	[ "$MWAN3_STARTUP" = 1 ] || mwan3_unlock "$ACTION" "$DEVICE-user"

	env -i ACTION="$ACTION" INTERFACE="$INTERFACE" DEVICE="$DEVICE" \
		/bin/sh /etc/mwan3.user
}

exit 0
