#!/bin/sh /etc/rc.common

START=95
STOP=10

USE_PROCD=1

PROG=/usr/bin/udp-proxy-2020

start_service() {
	local enabled
	local interfaces
	local port
	local log_level

	config_load udp-proxy-2020

	config_get_bool enabled main enabled 0
	[ "$enabled" -eq 1 ] || return 0

	config_get interfaces main interfaces "br-lan,wg0"
	config_get port main port "9003"
	config_get log_level main log_level "info"

	procd_open_instance

	procd_set_param command "$PROG" \
		-i "$interfaces" \
		-p "$port" \
		-L "$log_level"

	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1

	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "udp-proxy-2020"
}
