# GitHub/CI
"GitHub/CI":
- changed-files:
  - any-glob-to-any-file:
    - ".github/**"

# branches
"OpenWrt 23.05 (end of support)":
- base-branch:
  - "openwrt-23.05"
"OpenWrt 24.10":
- base-branch:
  - "openwrt-24.10"
"OpenWrt 25.12":
- base-branch:
  - "openwrt-25.12"
