#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0-or-later

USE_PROCD=1

START=81
STOP=81

NAME=bpftune
PROG=/usr/sbin/bpftune
CONFIG=/etc/config/bpftune

ARGS="-R -c /sys/fs/cgroup"
EXTRA_COMMANDS="checkconf"

checkconf() {
	config_load 'bpftune'
	config_get ARGS defaults command_args "$ARGS"
	$PROG -S $ARGS 2>&1
}

start_pre() {
	checkconf > /dev/null 2>&1
}

start_service()
{
	if ! start_pre; then
		return 1
	fi

	procd_open_instance
	procd_set_param file $CONFIG
	procd_set_param command $PROG $ARGS
	procd_set_param respawn
	procd_close_instance
}
