#!/bin/sh /etc/rc.common
# Copyright (C) 2020 OpenWrt.org

START=95

USE_PROCD=1
BIN=atftpd

start_service() {
	config_load atftpd
	config_get SRV service path "/srv/tftp"
	config_get PORT service port 69

	procd_open_instance
	procd_add_mdns "tftp" "udp" "$PORT" "daemon=atftpd"
	procd_set_param command $BIN "--no-fork" "--daemon" "--user" "root.root" "--port" "$PORT" "$SRV"
	procd_set_param respawn
	procd_close_instance
}
