
config stdiscosrv 'stdiscosrv'
	option enabled '0'
	option listen ':8443'
	option db_dir '/etc/stdiscosrv/db'

	# More info: https://docs.syncthing.net/users/stdiscosrv.html
	# option cert '/etc/stdiscosrv/cert.pem'
	# option key '/etc/stdiscosrv/key.pem'
	# option db_flush_interval '5m'
	# option metrics_listen ''

	# Running as 'root' is possible, but not recommended
	# option user 'syncthing'
	# option group 'syncthing'

	# CLI options with no value should be defined as booleans
	# option compression '0'
	# option debug '0'
	# option http '1'

	# Advanced options. Modify at your own risk.

	# More info: https://go.dev/doc/gc-guide#GOGC
	# option gc '0'

	# Max number of OS threads to use
	# 0 to match the number of CPUs (default)
	# >0 to explicitly specify concurrency
	# option maxprocs '0'

	# Soft memory limit in MB, 0 to disable
	# option memlimit '0'
