#!/usr/bin/env make

# Copyright 2019 Daniel Dickinson <cshored@thecshore.com>
# Released under term of the GNU General Public License version 2.0

# Let implicit rules take care of things
#
all: printscan-loadlp printscan-unloadlp saned-wrapper

