#!/bin/sh /etc/rc.common
#
# SPDX-License-Identifier: GPL-2.0-only

USE_PROCD=1
START=90

SWGP_GO_BIN="/usr/sbin/swgp-go"
SWGP_GO_CONF="/etc/swgp-go.json"

start_service() {
  procd_open_instance
  procd_set_param command $SWGP_GO_BIN -confPath $SWGP_GO_CONF -logLevel DEBUG
  procd_set_param file "$SWGP_GO_CONF"
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param respawn
  procd_close_instance
}
