#!/bin/sh /etc/rc.common

START=99

HOME=/root
MOZIOT_HOME="${HOME}/.mozilla-iot"
export PATH="/opt/mozilla-iot/gateway/tools:${PATH}"

run_app() {
	cd /opt/mozilla-iot/gateway

	echo "node version"
	node --version
	echo "npm version"
	npm --version
	echo "Starting gateway ..."
	npm start
}

start()
{
	mkdir -p /usr/etc/
	ln -sf /etc/openzwave /usr/etc/openzwave

	mkdir -p "${MOZIOT_HOME}/log"
	run_app &> "${MOZIOT_HOME}/log/run-app.log" &
}
