#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1

HOME=/root
MOZIOT_HOME="${HOME}/.mozilla-iot"
export PATH="/opt/mozilla-iot/gateway/tools:${PATH}"

start_service()
{
	mkdir -p /usr/etc/
	ln -sf /etc/openzwave /usr/etc/openzwave

	procd_open_instance mozilla-iot-gateway
	procd_set_param command /usr/bin/npm start --prefix /opt/mozilla-iot/gateway
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
