#!/bin/sh

# shellcheck source=/dev/null
. /lib/functions/keepalived/hotplug.sh

set_service_name firewall

set_skip_running_check
set_reload_if_sync

add_sync_file /etc/config/firewall

keepalived_hotplug
