#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0-only

START=95
STOP=10
USE_PROCD=1

start_service() {
	[ -c /dev/gl-e750-mcu ] || return 0

	config_load gl-e750-oled
	config_get_bool enabled main enabled 1
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command /usr/bin/ucode /usr/sbin/gl-e750-oled
	procd_set_param file /etc/config/gl-e750-oled
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "gl-e750-oled" "wireless"
}
