#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Chester A. Unal <chester.a.unal@arinc9.com>

[ "$ACTION" = "ifup" ] || exit

case "$INTERFACE" in
	wan*|wwan*|ifWan*|mob*_*)
		bsbf-plpmtu "$DEVICE" &
		;;
esac
