#!/bin/sh /etc/rc.common

USE_PROCD=1

START=99
STOP=01

prog_path="/usr/bin/iperf3"

service_data() {
  "${prog_path}" -v | grep -E '^iperf \d+\.\d+.*$'
}

start_service() {
  procd_open_instance
  procd_set_param command "${prog_path}" -s
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param respawn 10 10 10
  procd_set_param user nobody
  procd_close_instance
}

reload_service() {
  stop
  start
}
