#!/bin/sh /etc/rc.common

START=90
STOP=85

USE_PROCD=1

start_service()
{
	[ -f /etc/uci-defaults/yggdrasil ] && ( . /etc/uci-defaults/yggdrasil )

	procd_open_instance
	procd_set_param respawn

	procd_set_param command /usr/sbin/yggdrasil -useconffile /etc/yggdrasil.conf
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service()
{
	killall yggdrasil
}

reload_service()
{
	restart
}

service_triggers()
{
	procd_add_reload_trigger yggdrasil
}
