#!/bin/sh /etc/rc.common

USE_PROCD=1

START=50
STOP=51

PROG=/usr/sbin/stubby

start_service() {
  procd_open_instance stubby
  procd_set_param command /usr/sbin/stubby

  procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

  procd_set_param limits core="unlimited"

  procd_set_param file /etc/stubby/stubby.yml

  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param user stubby
  procd_close_instance
}

