#!/bin/sh /etc/rc.common

USE_PROCD=1
START=80
VERBOSE=0

start_service() {
	procd_open_instance
	procd_set_param command /usr/libexec/fwupd/fwupd
	[ "$VERBOSE" = 1 ] && procd_append_param command --verbose
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
	procd_close_instance
}
