#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2011 OpenWrt.org

START=60

NAME=zabbix_agentd
PROG=/usr/sbin/$NAME
CONFIG=/etc/$NAME.conf
SERVICE_PID_FILE=/var/run/$NAME.pid
LOCKER=/lib/zabbix/zlock.sh
. /lib/zabbix/functions.sh

start() {

	mkdir -p /var/run/${NAME}.conf.d
	uci2agentconfig $NAME 

	[ -f ${CONFIG} ] || return 1

	service_start ${PROG} -c ${CONFIG}
}

stop() {
	service_stop ${PROG}
	sleep 1
}

