#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1
PROG=/usr/bin/maddy
CONF_DIR=/etc/maddy
CONF_FILE=$CONF_DIR/maddy.conf
RUNTIME_DIR=/run/maddy
STATE_DIR=/var/lib/maddy
USER=maddy
GROUP=maddy

start_service() {
	config_load 'maddy'
	local config_name='config'

	local gc maxprocs memlimit

	uci_validate_section 'maddy' 'maddy' "$config_name" \
		'jail_mount:list(string)' \
		'jail_mount_rw:list(string)' \
		'gc:uinteger:0' \
		'maxprocs:uinteger:0' \
		'memlimit:uinteger:0'

	[ -d $RUNTIME_DIR ] || mkdir -m 0750 -p $RUNTIME_DIR
	[ -d $STATE_DIR ] || mkdir -m 0750 -p $STATE_DIR

	chown $USER:$GROUP -R $CONF_DIR
	chown $USER:$GROUP -R $STATE_DIR
	chown $USER:$GROUP -R $RUNTIME_DIR

	procd_open_instance "maddy"

	procd_set_param command "$PROG"
	procd_append_param command --config $CONF_FILE
	procd_append_param command run

	[ "$gc" -le 0 ] || procd_append_param env GOGC="$gc"
	[ "$maxprocs" -le 0 ] || procd_append_param env GOMAXPROCS="$maxprocs"
	[ "$memlimit" -le 0 ] || procd_append_param env GOMEMLIMIT="${memlimit}MiB"

	procd_set_param user "$USER"
	procd_set_param group "$GROUP"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_set_param file "$CONF_FILE"

	procd_add_jail maddy
	procd_add_jail_mount $CONF_DIR
	procd_add_jail_mount_rw $RUNTIME_DIR
	procd_add_jail_mount_rw $STATE_DIR
	config_list_foreach "$config_name" jail_mount procd_add_jail_mount
	config_list_foreach "$config_name" jail_mount_rw procd_add_jail_mount_rw
	procd_add_jail_mount /etc/ssl/certs

	procd_set_param capabilities "/etc/capabilities/maddy.json"
	procd_set_param no_new_privs 1

	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger 'maddy'
}
