#!/bin/sh /etc/rc.common
START=95
STOP=10

boot() {
	return 0
}

kill() {
	/usr/lib/ddns/dynamic_dns_updater.sh -- kill
	return 0
}

reload() {
	restart
}

restart() {
	/usr/lib/ddns/dynamic_dns_updater.sh -- stop
	sleep 1	# give time to shutdown
	/usr/lib/ddns/dynamic_dns_updater.sh -- start
}

start() {
	/usr/lib/ddns/dynamic_dns_updater.sh -- start
}

stop() {
	/usr/lib/ddns/dynamic_dns_updater.sh -- stop
	return 0
}
