#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/mihomo
CONFIG_FILE=/etc/mihomo/config.yaml

start_service() {
	config_load mihomo

	local enabled config_file
	config_get_bool enabled main enabled 0
	[ "$enabled" -eq 1 ] || return 0

	config_get config_file main config_file "$CONFIG_FILE"

	procd_open_instance
	procd_set_param command "$PROG" -d "$(dirname "$config_file")" -f "$config_file"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger mihomo
}
