#!/bin/sh /etc/rc.common

START=65

lease_file=/tmp/dhcpd.leases
config_file=/etc/dhcpd.conf
pid_file=/var/run/dhcpd.pid

start() {
	if [ ! -e $lease_file ]; then
		touch $lease_file
	fi

	/usr/sbin/dhcpd -q -cf $config_file -lf $lease_file -pf $pid_file $dhcp_ifs

	if [ $? -ne 0 ]; then
		return 1
	fi
}

stop() {
	if [ ! -e $pid_file ]; then
		return 1
	fi

	kill -9 `cat $pid_file`

	if [ $? -ne 0 ]; then
		return 1
	fi

	rm $pid_file
}
