#!/bin/sh /etc/rc.common
# Copyright (C) 2013-2017 OpenWrt.org

START=60
USE_PROCD=1

_log() {
	logger -p daemon.info -t prometheus-node-exporter-lua "$@"
}

append_addr() {
	has_listen_addr=1
	case "$1" in
		*:*) procd_append_param command "$listenflag" "[$1]:$port" ;;
		*) procd_append_param command "$listenflag" "$1:$port" ;;
	esac
}

start_service() {
	. /lib/functions/network.sh

	local interface port listenflag cert key bind4 bind6 omit_zero_values has_listen_addr

	config_load prometheus-node-exporter-lua.main
	config_get keepalive "main" http_keepalive 70
	config_get interface "main" listen_interface "loopback"
	config_get port "main" listen_port 9100
	config_get cert "main" cert
	config_get key "main" key
	config_get omit_zero_values "main" omit_zero_values 0

	procd_open_instance

	[ "$omit_zero_values" -eq 1 ] && procd_set_param env OMIT_ZERO_VALUES=1

	procd_set_param command /usr/sbin/uhttpd -f -c /dev/null -l / -L /usr/bin/prometheus-node-exporter-lua
	[ $keepalive -gt 0 ] && procd_append_param command -k $keepalive

	if [ -f "$cert" -a -f "$key" ]; then
		listenflag=-s
		procd_append_param command -C $cert -K $key
	else
		listenflag=-p
	fi

	config_list_foreach "main" listen_addresses append_addr
	[ -n "$has_listen_addr" ] || {
		[ "$interface" = "*" ] || {
			network_get_ipaddr  bind4 "$interface"
			network_get_ipaddr6 bind6 "$interface"
			[ -n "$bind4$bind6" ] || {
				_log "defering start until listen interface $interface becomes ready"
				procd_close_instance
				return 0
			}
		}

		if [ "$interface" = "*" ]; then
			procd_append_param command $listenflag $port
		else
			[ -n "$bind4" ] && procd_append_param command $listenflag $bind4:$port
			[ -n "$bind6" ] && procd_append_param command $listenflag [$bind6]:$port
		fi
	}

	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn

	procd_close_instance
}

service_triggers()
{
	local interface

	procd_add_reload_trigger "prometheus-node-exporter-lua"

	config_load prometheus-node-exporter-lua.main
	config_get interface "main" listen_interface "loopback"

	[ "$interface" = "*" ] || procd_add_reload_interface_trigger "$interface"
}
