#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

CONF="hev-socks5-tunnel"
PROG="/usr/bin/hev-socks5-tunnel"

start_instance() {
	local enabled conffile
	config_get_bool enabled "$1" enabled 0
	[ "$enabled" -eq 1 ] || return 0
	config_get conffile "$1" conffile

	if [ ! -f "$conffile" ]; then
		logger -t "$CONF" -p daemon.err "instance '$1' not started, conffile not found: '$conffile'"
		return 1
	fi

	procd_open_instance "$1"
	procd_set_param command "$PROG" "$conffile"
	procd_set_param file "$conffile"
	procd_set_param limits core="unlimited"
	procd_set_param limits nofile="1000000 1000000"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}

start_service() {
	config_load "$CONF"
	config_foreach start_instance instance
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}
