#!/bin/sh /etc/rc.common

START=19
USE_PROCD=1

start_service() {
	case "$(board_name)" in
		tplink,archer-be800*) ;;
		*) return 0 ;;
	esac

	procd_open_instance
	procd_set_param command /usr/sbin/ledmatrixd
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	procd_send_signal ledmatrixd '*' HUP
}

service_triggers() {
	procd_add_reload_trigger ledmatrix
}
