#!/bin/sh /etc/rc.common
# Copyright (C) 2013 Project Gluon

START=50

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

CRONDIR=/usr/lib/micron.d

start () {
	service_start /usr/sbin/micrond "$CRONDIR"
}

stop() {
	service_stop /usr/sbin/micrond
}
