#!/bin/sh /etc/rc.common

START=50
USE_PROCD=1

CRONDIR=/usr/lib/micron.d

service_triggers() {
	for file in $CRONDIR/*; do
		if [ -f /etc/config/${file##*/} ]; then
			procd_add_reload_trigger "${file##*/}"
		fi
	done
}

reload_service() {
	stop
	sleep 1
	start
}

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/micrond "$CRONDIR"
	procd_set_param respawn
	procd_close_instance
}
