# Template for config file /etc/klish/klishd.conf. It is used by the klishd daemon.

# klishd uses a UNIX domain socket to receive connections. It will create a
# filesystem entry to allow clients to find the connection point. By default,
# klishd uses the /tmp/klish-unix-socket path.
#UnixSocketPath=/tmp/klish-unix-socket

DBs=libxml2
DB.libxml2.XMLPath=/etc/klish/xml/
