#!/bin/sh

if [ "${INTERFACE}" = "loopback" ]; then
    exit 0
fi
if [ "${ACTION}" != "ifup" ] && [ "${ACTION}" != "ifupdate" ]; then
    exit 0
fi
if [ "${ACTION}" = "ifupdate" ] && [ -z "${IFUPDATE_ADDRESSES}" ] && [ -z "${IFUPDATE_DATA}" ]; then
    exit 0
fi

log() {
    logger -t "ip-timezone" "$@"
}

log_info() {
    log -p user.info "$*"
}

log_error() {
    log -p user.err "$*"
}

get_posix_timezone() {
    iana_timezone=$1
    tail -n1 /usr/share/zoneinfo/${iana_timezone}
}

endpoint="$(uci -q get ip-timezone.config.endpoint)"
if [ $? -ne 0 ]; then
    log_error "Endpoint not set"
    exit 1
fi

for i in {1..5}; do
    timezone_iana="$(wget --timeout=5 -qO- "${endpoint}")" && break || sleep 1
done

if [ -z "${timezone_iana}" ]; then
    log_error "Failed to get timezone"
    exit 1
fi

timezone_posix="$(get_posix_timezone ${timezone_iana})"
if [ $? -ne 0 ]; then
    log_error "Invalid timezone"
    exit 1
fi

if [ "${timezone_iana}" != "$(uci get system.@system[0].zonename)" ] || [  "${timezone_posix}" != "$(uci get system.@system[0].timezone)" ]; then
    log_info "Updating timezone, IANA: ${timezone_iana}, POSIX: ${timezone_posix}"
    uci set system.@system[0].zonename="${timezone_iana}"
    uci set system.@system[0].timezone="${timezone_posix}"
    uci commit system
    /etc/init.d/system reload
    /etc/init.d/cron restart
fi
