#!/bin/sh
# shellcheck disable=SC2015,SC3037,SC3043

readonly pbrFunctionsFile='/etc/init.d/pbr'
if [ -s "$pbrFunctionsFile" ]; then
# shellcheck source=../../etc/init.d/pbr
	. "$pbrFunctionsFile"
else
	printf "%b: pbr init.d file (%s) not found! \n" '\033[0;31mERROR\033[0m' "$pbrFunctionsFile"
fi

uci_set "$packageName" 'config' 'config_compat'  "$packageCompat"
uci_set "$packageName" 'config' 'config_version' "$PKG_VERSION"
uci_commit "$packageName"

exit 0
