#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2008 OpenWrt.org

START=90
STOP=01
USE_PROCD=1

CONF="umurmurd"
PROG="/usr/sbin/umurmurd"

start_service() {
        local user group
        user=umurmur group=umurmur

        procd_open_instance
        procd_set_param command $PROG -d

        procd_set_param user $user
        procd_set_param group $group
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param respawn

        procd_close_instance
}
