#!/bin/sh /etc/rc.common

START=90
STOP=10

USE_PROCD=1

PROG=/usr/sbin/umurmurd
CONF=/etc/umurmur/umurmur.conf

start_service() {
	procd_open_instance
	procd_set_param command $PROG -d -c $CONF
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger umurmur
}

reload_service() {
	procd_send_signal umurmur
}
