#!/bin/sh /etc/rc.common

USE_PROCD=1
START=97
STOP=01

PROG="/usr/bin/eventcat.lua"
PID_FILE="/var/run/eventcat.pid"

start_service() {
    procd_open_instance
    procd_set_param command $PROG
    procd_set_param file $CONFIG_FILE
    procd_set_param pidfile $PID_FILE
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance
}

reload_service() {
    procd_send_signal $PROG HUP
}
