#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=90
STOP=10

USE_PROCD=1
PROG=/usr/sbin/nullmailer-send
NAME=nullmailer

validate_section_nullmailer()
{
    if ! uci_validate_section nullmailer nullmailer "${1}" \
	'adminaddr:string' \
	'defaultdomain:string' \
	'defaulthost:string' \
	'queuetime:uinteger:60' \
	'sendtimeout:uinteger:3600' \
	'localfqdnhostname:string' \
	'runasuser:string:nullmailer' \
	'nullmailergroup:string:nullmailer'
    then
	return 1
    fi

   [ -z "$localfqdnhostname" ] && return 1

   return 0
}

validate_section_nullmailer_remote()
{
   if ! uci_validate_section nullmailer remote "${1}" \
	'smarthost:string' \
	'authlogin:bool:0' \
	'username:string' \
        'password:string' \
        'port:port:25'
    then
	return 1
    fi

   if [ -n "$password" ] && [ -z "$username" ]; then
       return 1
   fi

   [ -z "$smarthost" ] && return 1

   return 0
}

nullmailer_global() {
    local adminaddr defaultdomain defaulthost queuetime localfqdnhostname

    validate_section_nullmailer "${1}" || {
	echo "Validation failed"
	return 1
    }

    if [ -n "$adminaddr" ]; then
	echo "$adminaddr" >/var/etc/nullmailer/adminaddr
    fi

    if [ -n "$defaultdomain" ]; then
	echo "$defaultdomain" >/var/etc/nullmailer/defaultdomain
    fi

    if [ -n "$defaulthost" ]; then
	echo "$defaulthost" >/var/etc/nullmailer/defaulthost
    fi

    echo "${queuetime}" >/var/etc/nullmailer/pausetime

    echo "${sendtimeout}" >/var/etc/nullmailer/sendtimeout

    echo "${localfqdnhostname}" >/var/etc/nullmailer/helohost
    
    if [ -z "$defaulthost" ]; then
	echo "${localfqdnhostname}" >/var/etc/nullmailer/defaulthost
    fi
}

nullmailer_remote() {
    local smarthost authlogin username password port

    validate_section_nullmailer_remote "${1}" || {
	echo "Validation failed"
	return 1
    }

    echo "${smarthost} smtp --port=${port} ${authlogin:+--auth-login} ${username:+--user=$username} ${password:+--pass=$password}" >>/var/etc/nullmailer/remotes
    chown $runasuser:$(id -g $runasuser) /var/etc/nullmailer/remotes
    chmod 600 /var/etc/nullmailer/remotes
}

start_service() {
    local runasuser nullmailergroup

    rm -rf /var/etc/nullmailer
    mkdir -p /var/etc/nullmailer

    config_load "${NAME}"
    config_foreach nullmailer_global nullmailer || exit 1
    config_foreach nullmailer_remote remote || exit 1

    chown $runasuser:$nullmailergroup /var/etc/nullmailer
    chmod 700 /var/etc/nullmailer
    
    mkdir -p /var/spool/nullmailer/queue
    mkdir -p /var/spool/nullmailer/tmp
    rm -f /var/spool/nullmailer/trigger
    mkfifo /var/spool/nullmailer/trigger
    chown -R $runasuser:$nullmailergroup /var/spool/nullmailer
    chmod 4770 /var/spool/nullmailer/queue
    chmod 4770 /var/spool/nullmailer/tmp
    procd_open_instance
    procd_set_param command "$PROG" -s -u $runasuser
    procd_add_jail nullmailer log
    procd_add_jail_mount /var/etc/nullmailer /etc/nullmailer /usr/sbin/nullmailer-queue /usr/lib/nullmailer/smtp /etc/passwd /etc/group
    procd_add_jail_mount_rw /var/spool/nullmailer /tmp/spool/nullmailer
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "nullmailer"
    procd_add_validation validate_section_nullmailer
    procd_add_validation validate_section_nullmailer_remote
}

