#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=65
STOP=65

USE_PROCD=1
PROG=/sbin/ntpd
HOTPLUG_HELPER=/usr/sbin/ntpd.hotplug-helper

start_service() {
	mkdir -p /var/lib/ntp
	chown -R ntp:ntp /var/lib/ntp

	procd_open_instance
	procd_set_param command $PROG -g -u ntp:ntp -p /var/run/ntpd.pid -n
	procd_close_instance

	procd_open_instance
	procd_set_param command $HOTPLUG_HELPER
	procd_close_instance
}
