#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2019 OpenWrt.org

START=50

USE_PROCD=1

start_service() {
  [ -f /etc/syslog-ng.conf ] || return 1

  local timezone
  timezone="$(uci -q get 'system.@system[0].zonename')"
  [ -z "$timezone" ] && timezone="UTC"

  procd_open_instance
  procd_set_param command /usr/sbin/syslog-ng --foreground
  procd_set_param env "DEVICE_TZ=$timezone"
  procd_close_instance
}

service_triggers() {
  procd_add_reload_trigger "system"
}

reload_service() {
  /etc/init.d/syslog-ng restart
}
