#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2025 OpenWrt.org

# shellcheck shell=busybox

# shellcheck disable=SC2034
START=59

# shellcheck disable=SC2034
USE_PROCD=1

NAME=zabbix_server
PROG=/usr/sbin/${NAME}
CONFIG=/etc/${NAME}.conf
UCI_CONFIG=/etc/config/${NAME}
USER=zabbix-server

is_database_configured() {
	local no_db_password

	# We consider the database configured if there is a configured DBName,
	# DBUser, and DBPassword or 'no_db_password' is true in the UCI config
	if grep -q '[^#].*DBPassword=' "${CONFIG}" && grep -q '[^#].*DBName' "${CONFIG}"; then
		if ! grep -q '[^#].*DBUser=' "${CONFIG}"; then
			config_get_bool no_db_password general no_db_password 0
			if [ "$no_db_password" -eq 1 ]; then
				return 0
			else
				return 1
			fi
		else
			return 0
		fi
	else
		return 1
	fi
}

start_service() {
	local enabled never_root

	if [ ! -f "${CONFIG}" ]; then
		logger "Configuration file not found: '${CONFIG}'"
		return 1
	fi

	# Get enabled config option
	config_load "$NAME"
	config_get_bool never_root general never_root 1

	if ! is_database_configured; then
		logger "No database configuration for ${NAME}. Not starting."
		return 1
	fi

	mkdir -p "/var/run/$USER"
	chown $USER:$USER "/var/run/$USER"

	procd_open_instance
	procd_set_param command ${PROG} -c ${CONFIG} -f
	if [ "$never_root" -eq 1 ]; then
		procd_set_param user ${USER}
	fi
	procd_set_param limits nofile="16384 100000"
	procd_set_param file ${CONFIG}
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
