name: Test Formalities

on:
  pull_request:

jobs:
  build:
    name: Test Formalities
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Determine branch name
        run: |
          BRANCH="${GITHUB_BASE_REF#refs/heads/}"
          echo "Building for $BRANCH"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Test formalities
        run: |
          source .github/workflows/ci_helpers.sh

          RET=0
          for commit in $(git rev-list HEAD ^origin/$BRANCH); do
            info "=== Checking commit '$commit'"
            if git show --format='%P' -s $commit | grep -qF ' '; then
              err "Pull request should not include merge commits"
              RET=1
            fi

            author="$(git show -s --format=%aN $commit)"
            if echo $author | grep -q '\S\+\s\+\S\+'; then
              success "Author name ($author) seems ok"
            else
              err "Author name ($author) need to be your real name 'firstname lastname'"
              RET=1
            fi

            subject="$(git show -s --format=%s $commit)"
            if echo "$subject" | grep -q -e '^[0-9A-Za-z,+/_-]\+: ' -e '^Revert '; then
              success "Commit subject line seems ok ($subject)"
            else
              err "Commit subject line MUST start with '<package name>: ' ($subject)"
              RET=1
            fi

            body="$(git show -s --format=%b $commit)"
            sob="$(git show -s --format='Signed-off-by: %aN <%aE>' $commit)"
            if echo "$body" | grep -qF "$sob"; then
              success "Signed-off-by match author"
            else
              err "Signed-off-by is missing or doesn't match author (should be '$sob')"
              RET=1
            fi
          done

          exit $RET

      - name: Determine changed packages
        run: |
          # only detect packages with changes
          PKG_ROOTS=$(find . -name Makefile | \
            grep -v ".*/src/Makefile" | \
            sed -e 's@./\(.*\)/Makefile@\1/@')
          CHANGES=$(git diff --diff-filter=d --name-only origin/$BRANCH...)

          for ROOT in $PKG_ROOTS; do
            for CHANGE in $CHANGES; do
              if [[ "$CHANGE" == "$ROOT"* ]]; then
                if grep -q '$(AUTORELEASE)' "$ROOT/Makefile"; then
                  CONTAINS_AUTORELEASE+="$ROOT"
                fi
                break
              fi
            done
          done

          if [ -n "$CONTAINS_AUTORELEASE" ]; then
            cat > "$GITHUB_WORKSPACE/pr_comment.md" << EOF
          Please do no longer set *PKG_RELEASE* to *AUTORELEASE* as the
          feature is deprecated. Please use an integer instead. Below is a
          list of affected packages including correct *PKG_RELEASE*:

          EOF
          else
            echo "No usage of *AUTORELEASE* found in changes" > "$GITHUB_WORKSPACE/pr_comment.md"
          fi

          for ROOT in $CONTAINS_AUTORELEASE; do
            echo -n "  - ${ROOT}Makefile: PKG_RELEASE:=" >> "$GITHUB_WORKSPACE/pr_comment.md"
            last_bump="$(git log --pretty=format:'%h %s' "$ROOT" |
              grep --max-count=1 -e ': [uU]pdate to ' -e ': [bB]ump to ' |
              cut -f 1 -d ' ')"

            if [ -n "$last_bump" ]; then
              echo -n $(($(git rev-list --count "$last_bump..HEAD" "$ROOT") + 2)) >> "$GITHUB_WORKSPACE/pr_comment.md"
            else
              echo -n $(($(git rev-list --count HEAD "$ROOT") + 2)) >> "$GITHUB_WORKSPACE/pr_comment.md"
            fi
            echo >> "$GITHUB_WORKSPACE/pr_comment.md"
          done

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: 'pr_comment.md'
          edit-mode: replace
