name: Test and Build

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Feeds Package Test Build
    uses: openwrt/actions-shared-workflows/.github/workflows/multi-arch-test-build.yml@main
