name: Test and Build

on:
  check_suite:
    types: [completed]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: Feeds Package Test Build
    if: ${{ github.event.check_suite.conclusion == 'success' }}
    uses: openwrt/actions-shared-workflows/.github/workflows/multi-arch-test-build.yml@main
